services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  web:
    build:
      context: ./web
      dockerfile: Dockerfile

    depends_on:
      - api
    volumes:
      - ./web:/web
      - /web/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
