version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4000:8081"
    environment:
      - NODE_ENV=development
