services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/api/src
      - ./api/utils:/api/utils
      - ./api/server.ts:/api/server.ts
      - ./api/prisma:/api/prisma
      - ./api/package.json:/api/package.json
      - ./api/package-lock.json:/api/package-lock.json
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/app:/web/app
    depends_on:
      - api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
