services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/api/src
      - ./api/server.ts:/api/server.ts
      - ./api/prisma:/api/prisma
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile

    depends_on:
      - api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
