name: CI - API

on:
  pull_request:
    branches:
      - dev
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FRONTEND_URL: http://127.0.0.1:3000 # Needed for cors plugin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: api
        run: npm install

      - name: Run Typescript check
        working-directory: api
        run: npm run check:ts

      - name: Start API
        working-directory: api
        run: npm run test:api-start

      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:3000

      - name: Run tests
        working-directory: api
        run: npm run test
