name: Linting Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install projects dependencies
        run: |
          cd web && npm ci
          cd ../api && npm ci
          cd ../database && npm ci

      - name: Lint Web
        run: |
          cd web
          npm run web:lint

      - name: Lint API
        run: |
          cd api
          npm run lint

      - name: Lint Database
        run: |
          cd database
          npm run lint
